@startuml "État des bandes"
' Définir le style global
skinparam {
    backgroundColor 007acc
    ' 007acc = oui
    ' 92cc00ff = non
    shadowing true
    ' oui
    FontName "Consolas"
    ArrowColor ffffffff
    ' #ffffffff
    ArrowFontColor 8598d6ff
    ' #8598d6ff
    StartColor ff02c4ff
    ' #ff02c4ff
    EndColor ff02c4
    ' #ff02c4
}
' Style pour les states
skinparam state {
    BackgroundColor 3e3e4eff
    ' #3e3e4eff
    fontColor 007acc
    ' #007acc
    BorderColor 007acc
    ' #007acc
    FontName "Consolas"
    FontSize 12
    FontStyle bold
}
<style>
mainframe {
  LineColor 007acc
  ' #007acc
  LineThickness 2.0
  FontColor 9ed1f3ff
  ' #9ed1f3ff
  FontSize 25
  FontStyle italic
  ' non
  Margin 50
  ' non
  Padding 100
  ' non
  backgroundColor 000000ff
  ' #000000
}
</style>
mainframe \n\t**État des bandes**\t\n

    state ATTENTE : affichage seul
    state SELECTION : effet de surbrillance actif
    state DEPLACEMENT : gauche/droite
    state CONTRAT : amortissement de la perte des fans

    [*] --> ATTENTE
    ATTENTE -> SELECTION : Choix d'une bande\n[souris ou arcade appuyé]
    SELECTION -> DEPLACEMENT : fleches\n\t[gauche/droite ou arcade]\t
    DEPLACEMENT --> SELECTION :immobilisation\n [animation déplacement terminée]
    SELECTION -> CONTRAT :ajout à la collection\n[fait partie du CONTRAT ?]
    CONTRAT -> [*] #007acc
@enduml

/'

git add .
git fetch origin
git merge origin/main -m "merge avec le bot"
git push

'/