@startuml "État des bandes"
state attente
state selectionne
state deplacement : gauche/droite
state Contrat

attente -> selectionne : Clic\n[souris ou arcade]
selectionne -> deplacement : fleches\n[gauche/droite ou arcade]
deplacement --> selectionne :immobilisation\n[animation déplacement terminée]
selectionne -> Contrat :ajout à la collection\n[fait partie du contrat ?]
@enduml