name: Auto UML Renderer

on:
  push:
    paths:
      - '**/*.puml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PlantUML and Graphviz
        run: sudo apt-get update && sudo apt-get install -y plantuml graphviz

      - name: Generate UML diagrams
        run: |
          mkdir -p docs/uml
          cd docs/uml/puml
          for f in *.puml; do
            plantuml -tpng "$f" -o ../
          done

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/uml/*.png
          git diff --cached --quiet || git commit -m "🔄 Update UML diagrams"
          git push || echo "Nothing to push"
